Revert "fix: switch rebased-bin to appimage packaging"
This reverts commit 9e99d52c22d12a9538df75b2173db14c73149b39.

# Conflicts:
#	packages/rebased-bin/.SRCINFO
#	packages/rebased-bin/PKGBUILD
#	packages/rebased-bin/update.sh

diff --git a/packages/rebased-bin/PKGBUILD b/packages/rebased-bin/PKGBUILD
--- a/packages/rebased-bin/PKGBUILD
+++ b/packages/rebased-bin/PKGBUILD
@@ -13,37 +13,36 @@ optdepends=('xdg-utils: open URLs from the IDE')
 provides=('rebased')
 conflicts=('rebased')
 options=('!strip')
-source=("${_pkgname}-${pkgver}-${CARCH}.AppImage::https://github.com/DetachHead/rebased/releases/download/${pkgver}/Rebased-x86_64.AppImage")
-sha256sums=('38c242808e3fdb109d92f90a221d03a2fce8ad0e5e1175e08b5bbd9f212e8a3e')
+source=("${_pkgname}-${pkgver}.tar.gz::https://github.com/DetachHead/rebased/releases/download/${pkgver}/rebased.tar.gz")
+sha256sums=('f3d8f6255f4e31ee51e9df99040e76cd09949301754022ddee0ba9de1b0e1413')
 
 package() {
-  local appimage="${srcdir}/${_pkgname}-${pkgver}-${CARCH}.AppImage"
-  local extract_dir="${srcdir}/appimage-extract"
+  source_root=""
 
-  chmod +x "${appimage}"
-  rm -rf "${extract_dir}"
-  install -dm755 "${extract_dir}"
+  for candidate in "${srcdir}"/idea-IC-* "${srcdir}"/ideaIC-* "${srcdir}"/rebased* "${srcdir}"/Rebased*; do
+    if [[ -d "${candidate}" ]]; then
+      source_root="${candidate}"
+      break
+    fi
+  done
 
-  (
-    cd "${extract_dir}"
-    APPIMAGE_EXTRACT_AND_RUN=1 "${appimage}" --appimage-extract >/dev/null
-  )
+  if [[ -z "${source_root}" ]]; then
+    printf 'failed to locate extracted source tree\n' >&2
+    return 1
+  fi
 
   install -dm755 "${pkgdir}/opt/${_pkgname}"
-  install -Dm755 "${appimage}" "${pkgdir}/opt/${_pkgname}/Rebased-x86_64.AppImage"
+  cp -a "${source_root}/." "${pkgdir}/opt/${_pkgname}/"
 
-  install -Dm755 /dev/stdin "${pkgdir}/usr/bin/rebased" <<'SCRIPT'
-#!/bin/sh
-exec env APPIMAGE_EXTRACT_AND_RUN=1 APPIMAGELAUNCHER_DISABLE=1 \
-  /opt/rebased/Rebased-x86_64.AppImage "$@"
-SCRIPT
+  install -dm755 "${pkgdir}/usr/bin"
+  ln -s "/opt/${_pkgname}/bin/idea" "${pkgdir}/usr/bin/rebased"
 
-  install -Dm644 "${extract_dir}/squashfs-root/usr/bin/idea.svg" "${pkgdir}/usr/share/icons/hicolor/scalable/apps/rebased.svg"
-  install -Dm644 "${extract_dir}/squashfs-root/rebased.png" "${pkgdir}/usr/share/pixmaps/rebased.png"
-  install -Dm644 "${extract_dir}/squashfs-root/usr/LICENSE.txt" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE.txt"
-  install -Dm644 "${extract_dir}/squashfs-root/usr/NOTICE.txt" "${pkgdir}/usr/share/licenses/${pkgname}/NOTICE.txt"
+  install -Dm644 "${source_root}/bin/idea.svg" "${pkgdir}/usr/share/icons/hicolor/scalable/apps/rebased.svg"
+  install -Dm644 "${source_root}/bin/idea.png" "${pkgdir}/usr/share/pixmaps/rebased.png"
+  install -Dm644 "${source_root}/LICENSE.txt" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE.txt"
+  install -Dm644 "${source_root}/NOTICE.txt" "${pkgdir}/usr/share/licenses/${pkgname}/NOTICE.txt"
 
-  install -Dm644 /dev/stdin "${pkgdir}/usr/share/applications/rebased.desktop" <<DESKTOP
+  install -Dm644 /dev/stdin "${pkgdir}/usr/share/applications/rebased.desktop" <<'DESKTOP'
 [Desktop Entry]
 Type=Application
 Version=1.0
@@ -56,6 +55,5 @@ StartupNotify=true
 StartupWMClass=jetbrains-rebased
 Categories=Development;IDE;VersionControl;
 Keywords=git;vcs;jetbrains;
-X-AppImage-Version=${pkgver}
 DESKTOP
 }
